// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvrxmdmnefwtyvhubsnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2cnhtZG1uZWZ3dHl2aHVic25mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNTEyMTUsImV4cCI6MjA1NDkyNzIxNX0.KGPVFG7bo0GHCwqDX_ijK_InJzzrFhodiXaJcZaF7gU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});